class_register/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.about, name='about'),
  # path('about/', views.about, name='about'),

  # ________ Instructors _________
  path('instructors/', views.instructors_index, name='instructors_index'),
  path('instructors/<int:instructor_id>', views.instructors_detail, name='instructors_detail'),
  path('instructors/create/', views.InstructorCreate.as_view(), name='instructors_create'),
  path('instructors/<int:pk>/update/', views.InstructorUpdate.as_view(), name='instructors_update'),
  path('instructors/<int:pk>/delete/', views.InstructorDelete.as_view(), name='instructors_delete'),
  
  # ________ Classes _________

  path('classes/', views.classes_index, name='classes_index'),
  path('classes/<int:class_id>', views.classes_detail, name='classes_detail'),
  path('classes/create/', views.ClassCreate.as_view(), name='classes_create'),
  path('classes/<int:pk>/update/', views.ClassUpdate.as_view(), name='classes_update'),
  path('classes/<int:pk>/delete/', views.ClassDelete.as_view(), name='classes_delete'),

  # ________ Associated Links _________

  path('classes/<int:class_id>/assoc_student/<int:student_id>/', views.assoc_student, name='assoc_student'),
  path('classes/<int:class_id>/assoc_student/<int:student_id>/delete/', views.assoc_student_delete, name='assoc_student_delete'),

# add instructor to class?
  path('classes/<int:class_id>/assoc_instructor_to_class/<int:instructor_id>/', views.assoc_instructor_to_class, name='assoc_instructor_to_class'),
  path('classes/<int:class_id>/assoc_instructor_to_class/<int:instructor_id>/delete/', views.assoc_instructor_to_class_delete, name='assoc_instructor_to_class_delete'),
# 
# add class to instructor?
  # path('instructors/<int:instructor_id>/assoc_class_to_instructor/<int:class_id>/', views.assoc_class_to_instructor, name='assoc_class_to_instructor'),
  # path('instructors/<int:instructor_id>/assoc_class_to_instructor_delete/<int:class_id>/delete', views.assoc_class_to_instructor_delete, name='assoc_class_to_instructor_delete'),
# 

  path('students/<int:student_id>/assoc_class/<int:class_id>/', views.assoc_class, name='assoc_class'),
  path('students/<int:student_id>/assoc_class/<int:class_id>/delete/', views.assoc_class_delete, name='assoc_class_delete'),

  # ________ Photo Handling _________

  path('students/<int:student_id>/add_photo/', views.add_photo, name='add_photo'),
  # path('instructors/<int:instructor_id>/add_photo/', views.add_photo, name='add_photo'),

  # ________ Students _________

  # path('students/', views.StudentList.as_view(), name='students_index'),
  # path('students/<int:pk>', views.StudentDetail.as_view(), name='students_detail'),
  path('students/', views.students_index, name='students_index'),
  path('students/<int:student_id>', views.students_detail, name='students_detail'),
  path('students/create', views.StudentCreate.as_view(), name='students_create'),
  path('students/<int:pk>/update/', views.StudentUpdate.as_view(), name='students_update'),
  path('students/<int:pk>/delete/', views.StudentDelete.as_view(), name='students_delete'),

  # ________ Sign-Up _________

  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

DAYS = (
  ('Mon', 'Monday'),
  ('Tue', 'Tuesday'),
  ('Wed', 'Wednesday'),
  ('Thu', 'Thursday'),
  ('Fri', 'Friday'),
  ('Sat', 'Saturday'),
  ('Sun', 'Sunday'),
)

class Student(models.Model):
  name = models.CharField(max_length=150)
  email = models.EmailField(max_length=200)
  phone = models.CharField(max_length=13)
  age = models.IntegerField()
  address = models.CharField(max_length=250)
  city = models.CharField(max_length=150)
  state = models.CharField(max_length=2)
  zip = models.CharField(max_length=5)
  def __str__(self):
    return f"{self.name}"
  def get_absolute_url(self):
    return reverse('students_detail', kwargs={'pk': self.id})

class Instructor(models.Model):
  name = models.CharField(max_length=150)
  email = models.EmailField(max_length=200)
  phone = models.CharField(max_length=13)
  # classes = models.ManyToManyField(Class, related_name='classes')
  def __str__(self):
    return f"{self.name}"
  def get_absolute_url(self):
    return reverse('instructors_detail', kwargs={'pk': self.id})

class Class(models.Model):
  title = models.CharField(max_length=200)
  studio = models.IntegerField()
  # day_of_week = models.CharField(max_length=25)
  day_of_week = models.CharField(
    max_length=3, choices=DAYS, default=DAYS[0][0]
  )
  start_time = models.CharField(max_length=10)
  end_time = models.CharField(max_length=10)
  instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
  # instructors = models.CharField(max_length=150)
  # instructors = models.ManyToManyField(Instructor, related_name='classes')
  students = models.ManyToManyField(Student, related_name='classes')
  def __str__(self):
    return f"{self.title}"
  def get_absolute_url(self):
    return reverse('classes_detail', kwargs={'pk': self.id})


class Photo(models.Model):
  url = models.CharField(max_length=200)
  student = models.ForeignKey(Student, on_delete=models.CASCADE)
  # instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
  def __str__(self):
    return f"photo for student_id: {self.student_id} @{self.url}"

main_app/views.py
from django.shortcuts import render, redirect

# from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# from django.views.generic.detail import DetailView

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Class, Student, Instructor, Photo

import uuid
import boto3

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'class-register'

# Create your views here.
# def home(request):
#   return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def classes_index(request):
  classes = Class.objects.all()
  instructor = Instructor.objects.all()
  return render(request, 'classes/index.html', { 'classes': classes, 'instructor': instructor })
  # add more here later

@login_required
def classes_detail(request, class_id):
  classes = Class.objects.get(id=class_id)
  students = Student.objects.exclude(id__in=classes.students.all().values_list('id'))
  # instructor = Instructor.objects.exclude(id__in=classes.instructor.all().values_list('id'))
  instructor = Instructor.objects.all()
  return render(request, 'classes/detail.html', {
    'class': classes, 'students': students, 'instructor': instructor
  })

@login_required
def students_index(request):
  students = Student.objects.all()
  return render(request, 'students/index.html', { 'students': students })

@login_required
def students_detail(request, student_id):
  student = Student.objects.get(id=student_id)
  classes = Class.objects.exclude(id__in=student.classes.all().values_list('id'))
  return render(request, 'students/detail.html', {
    'student': student, 'classes': classes 
  })

@login_required
def instructors_index(request):
  instructors = Instructor.objects.all()
  # 
  return render(request, 'instructors/index.html', { 'instructors': instructors })

@login_required
def instructors_detail(request, instructor_id):
  instructor = Instructor.objects.get(id=instructor_id)
  # classes = Class.objects.exclude(id__in=instructor.classes.all().values_list('id'))
  return render(request, 'instructors/detail.html', {
    'instructor': instructor
    # 'instructor': instructor, 'classes': classes 
  })

# ________ Many-to-Many Associations __________

@login_required
def assoc_student(request, class_id, student_id):
  Class.objects.get(id=class_id).students.add(student_id)
  return redirect('classes_detail', class_id=class_id)

@login_required
def assoc_student_delete(request, class_id, student_id):
  Class.objects.get(id=class_id).students.remove(student_id)
  return redirect('classes_detail', class_id=class_id)

@login_required
def assoc_class(request, student_id, class_id):
  Student.objects.get(id=student_id).classes.add(class_id)
  return redirect('students_detail', student_id=student_id)

@login_required
def assoc_class_delete(request, student_id, class_id):
  Student.objects.get(id=student_id).classes.remove(class_id)
  return redirect('students_detail', student_id=student_id)


# Add Instructors Associatios Here
@login_required
def assoc_instructor_to_class(request, class_id, instructor_id):
  Class.objects.get(id=class_id).instructors.add(instructor_id)
  return redirect('classes_detail', class_id=class_id)

@login_required
def assoc_instructor_to_class_delete(request, class_id, instructor_id):
  Class.objects.get(id=class_id).instructors.remove(instructor_id)
  return redirect('classes_detail', class_id=class_id)

@login_required
def assoc_class_to_instructor(request, instructor_id, class_id):
  Instructor.objects.get(id=instructor_id).classes.add(class_id)
  return redirect('instructors_detail', instructor_id=instructor_id)

@login_required
def assoc_class_to_instructor_delete(request, instructor_id, class_id):
  Instructor.objects.get(id=instructor_id).classes.remove(class_id)
  return redirect('instructors_detail', instructor_id=instructor_id)

# ________ Sign Up Function __________

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('about')
    else:
      error_message = 'Invalid credentials. Please try login again.'
  form = UserCreationForm()
  context = { 'form': form, 'error_message': error_message }
  return render(request, 'registration/signup.html', context)

# ________ Photo Handling __________
@login_required
def add_photo(request, student_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      photo = Photo(url=url, student_id=student_id)
      photo.save()
    except Exception as error:
      print('An error occurred uploading file to S3', error)
      return redirect('students_detail', student_id=student_id)
  return redirect('students_detail', student_id=student_id)    

# ________ Class Declaration CRUD Functionality / Classes __________

class ClassCreate(LoginRequiredMixin, CreateView):
  model = Class
  fields = ['title', 'studio', 'day_of_week', 'start_time', 'end_time', 'instructor']
  success_url = '/classes/'

class ClassUpdate(LoginRequiredMixin, UpdateView):
  model = Class
  fields = ['title', 'studio', 'day_of_week', 'start_time', 'end_time', 'instructor']
  success_url = '/classes/'

class ClassDelete(LoginRequiredMixin, DeleteView):
  model = Class
  success_url = '/classes/'

# ________ Class Declaration CRUD Functionality / Students __________

class StudentCreate(LoginRequiredMixin, CreateView):
  model = Student
  fields = ['name', 'email', 'phone', 'age', 'address', 'city', 'state', 'zip']
  success_url = '/students/'

class StudentUpdate(LoginRequiredMixin, UpdateView):
  model = Student
  fields = ['name', 'email', 'phone', 'age', 'address', 'city', 'state', 'zip']
  success_url = '/students/'

class StudentDelete(LoginRequiredMixin, DeleteView):
  model = Student
  success_url = '/students/'

# ________ Class Declaration CRUD Functionality / Instructor __________

class InstructorCreate(LoginRequiredMixin, CreateView):
  model = Instructor
  fields = ['name', 'email', 'phone']
  success_url = '/instructors/'

class InstructorUpdate(LoginRequiredMixin, UpdateView):
  model = Instructor
  fields = ['name', 'email', 'phone']
  success_url = '/instructors/'

class InstructorDelete(LoginRequiredMixin, DeleteView):
  model = Instructor
  success_url = '/instructors/'

main_app/templates/students/detail.html
{% extends 'base.html' %} {% block content %}


<div class="container">
  <div class="row justify-content-md-center">
    <div class="card" style="margin: 5%; background-color: #DCD7C9;">
      <div class="card-body">
        <h1 class="card-title">{{ student.name }}</h1>
        <div>
          <a href="{% url 'students_update' student.id %}" style="color: #576F72">Edit</a> | 
          <a href="{% url 'students_delete' student.id %}" style="color: #576F72">Delete</a>
        </div>
        <div class="row">
          <!-- Display Student Details -->
          <div class="col-6">
            <div class="card" style="background-color: #DCD7C9;">
              <div class="card-body">
                <span>General / Contact Information</span>
                <ul style="list-style: none;">
                  <li>age: {{ student.age }}</li>
                  <li>email: {{ student.email }}</li>
                  <li>phone: {{ student.phone }}</li>
                </ul>
                <span>Address</span>
                <ul style="list-style: none;">
                  <li>{{ student.address }}</li>
                  <li>{{ student.city }}, {{ student.state }}</li>
                  <li>{{ student.zip }}</li>
                </ul>
              </div>
            </div>
          </div>
          <!-- Photo Addition / Display -->
          <div class="col-4 offset-1">
            <div class="card" style="background-color: #DCD7C9;">
              {% for photo in student.photo_set.all %}
              <img src="{{ photo.url }}" class="card-img-top" alt="{{ student.name }}">
              {% empty %}
              <div>No Photo</div>
              {% endfor %}            
            </div>
            <form 
              action="{% url 'add_photo' student.id %}" 
              method="POST"
              enctype="multipart/form-data"
            >
            {% csrf_token %}
              <input type="file" name="photo-file">
              <input type="submit" class="btn btn-outline-success" value="Upload Photo" />
            </form>     
          </div>
        </div>

        <hr>
        <!-- See / Remove Classes from this Student -->
        <div class="row">
          <div>
            <h5>{{ student.name }}'s Classes</h5>
            {% if student.classes.count %} {% for class in student.classes.all %}
            <div>
              <form
              action="{% url 'assoc_class_delete' student.id class.id %}"
              method="POST"
              >
              {% csrf_token %}
              <span>
                <button type="submit" class="btn btn-outline-danger btn-sm">-</button>
                <a href="{% url 'classes_detail' class.id %}" style="color: #576F72">
                  {{ class.title }}
                </a>
                <span>{{ class.day_of_week }}, {{ class.start_time }}pm - {{ class.end_time }}pm</span>
              </span>
            </form>
          </div>
          {% endfor %} {% else %}
          <h6>( Not Enrolled in Any Classes )</h6>
          {% endif %}
          </div>        
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Add Classes to this Student -->
<div class="container">
  <div class="row justify-content-md-center">
    <div class="card" style="margin: 5%; background-color: #DCD7C9;">
      <div class="card-body">
        <div>
          <h5>Available Classes:</h5>
          {% if classes.count %} {% for class in classes.all %}
          <div>
            <form action="{% url 'assoc_class' student.id class.id %}" method="POST">
              {% csrf_token %}
              <span>
                <button type="submit" class="btn btn-outline-success btn-sm">+</button>
                <a href="{% url 'classes_detail' class.id %}" style="color: #576F72">
                  {{ class.title }}
                </a>
                <span>{{ class.day_of_week }}, {{ class.start_time }}pm - {{ class.end_time }}pm</span>
              </span>
            </form>
          </div>
          {% endfor %} {% else %}
          <h6>( No Available Classes )</h6>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/students/index.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row justify-content-md-center">
    <div class="card" style="margin: 5%; background-color: #DCD7C9;">
      <div class="card-body">
        <h1 class="card-title">Students</h1>
        <a href="{% url 'students_create' %}" style="color: #576F72">Add a Student</a>
        <br />

        {% for student in students %}
        <div class="card" style="background-color: #DCD7C9;">
          <a href="{% url 'students_detail' student.id %}" style="color: #576F72">
            <div class="card-body">
              <span>{{ student.name }}</span>
            </div>
          </a>
        </div>
        <br />
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}